### ISSUE TITLE
 ERROR: Failed building wheel for llama-cpp-python

### ISSUE THREAD

**Issue by Mage-Enderman** [badgids/OpenKlyde#1]
-- Trying 'NMake Makefiles (Visual Studio 15 2017 x64 v141)' generator - failure
      --------------------------------------------------------------------------------

                      ********************************************************************************
                      scikit-build could not get a working generator for your system. Aborting build.

                      Building windows wheels for Python 3.11 requires Microsoft Visual Studio 2022.
      Get it with "Visual Studio 2017":

        https://visualstudio.microsoft.com/vs/

      Or with "Visual Studio 2019":

          https://visualstudio.microsoft.com/vs/

      Or with "Visual Studio 2022":

          https://visualstudio.microsoft.com/vs/

                      ********************************************************************************
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

**Comment by badgids** [comment]
You need to install Microsoft Visual Studio 2022 build tools.

Navigate to: 
[https://visualstudio.microsoft.com/vs/](https://visualstudio.microsoft.com/vs/), then download and install Visual Studio 2022 Community Edition.  Select the Desktop development with C++ by clicking the checkbox. Make sure you allow the installer to add the build tools to your path.

Cheers!
