### ISSUE TITLE
ERROR: Could not build wheels for llama-cpp-python

### ISSUE THREAD

**Issue by xhatz** [badgids/OpenKlyde#12]
Hello! I am getting this error after trying to install requirements:

`ERROR: Failed building wheel for coqui-tts
Failed to build llama-cpp-python coqui-tts
ERROR: Could not build wheels for llama-cpp-python, coqui-tts, which is required to install pyproject.toml-based projects`

**Comment by badgids** [comment]
Sounds like you don't have Visual Studio and the C++ build tools installed on your machine. If you do, then make sure your environment variables are set up and pointing to the correct directories.

**Comment by xhatz** [comment]
Thank you!
