### ISSUE TITLE
It won't every reply

### ISSUE THREAD

**Issue by Mage-Enderman** [badgids/OpenKlyde#3]
Discord Bot is up and running.
Task exception was never retrieved
future: <Task finished name='Task-13' coro=<send_to_model_queue() done, defined at G:\AI\OpenKlyde\bot.py:170> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "G:\AI\OpenKlyde\bot.py", line 178, in send_to_model_queue
    await functions.add_to_conversation_history(content["user_input"], content["user"], content["user"])
  File "G:\AI\OpenKlyde\functions.py", line 155, in add_to_conversation_history
    await append_text_file(file_name, content)
  File "G:\AI\OpenKlyde\functions.py", line 200, in append_text_file
    with open(file, 'a+', encoding="utf-8") as context:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'context\\Mage_Enderman.txt'

**Comment by badgids** [comment]
Looks like it failed to create the context directory on your machine. Manually create a subdirectory in the bot's root directory named context and try again.

**Comment by Mage-Enderman** [comment]
Thank you that worked
I'm curious which of these is max output tokens?
"max_length": 1095,
"genamt": 1095,
And is there the option to "Auto-Adjust Limits"?

**Comment by badgids** [comment]
Max_length is the maximum allowed reply in characters (limited by Discords 2000), and the genamt is the maximum generated amount. If the generated tokens goes over the Discord's character limit, it will error, and possibly crash. Still working on this part. 😂
