### ISSUE TITLE
Can you add an option for it to continue?

### ISSUE THREAD

**Issue by Mage-Enderman** [badgids/OpenKlyde#5]
Sometimes depending on the max token amount it can get cutoff
In the kobold ui you can just hit send again and it'll continue from where it left off but I don't think there's a way to do that over discord rn

**Comment by badgids** [comment]
Right now you can reply with "continue". Ultimately, the idea is to just send multiple messages if the response goes over Discord's 2k character limit.

**Comment by Mage-Enderman** [comment]
I'm not even talking about Discords limit I mean the token limit sometimes it cuts itself off if you set it lower but it's personally insane to me to have it ALWAYS be like 200 or something

**Comment by badgids** [comment]
Yeah, I usually keep my response limit around 500 tokens until I get the multiple replies figured out correctly. In the meantime, replying continue seems to work ~90% of the time.

**Comment by Mage-Enderman** [comment]
I think 500 tokens would take a little too long on my computer. so I guess I'll suffer with it being cutoff occasionally with 100 max tokens

**Comment by badgids** [comment]
What are your machines specs? I find launching from the command line to be a bit more customizable than the koboldcpp UI launcher.
 I have an i9 with 8 cores 16 threads, 64GB ram and a 4090, but I use the same settings for a 3060  too.

```sh
koboldcpp --stream --threads 10 --ropeconfig 0.25 10000 --unbantokens --smartcontext --useclblast 0 0 --gpulayers 100 "/path/to/your/LLM/your_quantized_ggml.bin"
```

You can see all the available command line options by typing ``` koboldcpp --help``` on the command line.

I add koboldcpp to my system path so I can launch it from any directory.

Cheers!
