### ISSUE TITLE
How to connect to backend?

### ISSUE THREAD

**Issue by unsureboolean** [badgids/OpenKlyde#6]
Hi, I was able to get the bot running and connected to discord, but I'm not sure where to put the api key or otherwise link it up to the LLM I'm running locally.  Where/how do we input that info?

**Comment by badgids** [comment]
The only API key you need to add is a Discord APY in the **bot.py** file on line 19.

```python
discord_api_key = "Place your Discord Bot API Key here"
```

Other than that, you just load up the LLM of your choice inside koboldcpp. The bot expects the koboldcpp api server to be running on port 5001, which is the default for koboldcpp.

If it's not working, it may be a firewall isue, or an IP address error.

To change the port or url to the LLM server, you'll find that on line three of the **text-default.json** file in the **/cofigurations** directory. The line looks like this:

```json
"address": "http://localhost:5001/api/v1/",
```
If for some reason it's not seeing Koboldcpp, and it's running on the default port, you may need to change the IP address to:

```json
"address": "http://0.0.0.0:5001/api/v1/",
```

or

```json
"address": "http://127.0.0.1:5001/api/v1/",
```

If you have koboldcpp running on a different machine, and/or a different port than the default, you wil need to change this line to match the correct IP address and port number.

Cheers!

**Comment by tarangot** [comment]
I'd love to see instructions for using this with WebUI.

**Comment by badgids** [comment]
> I'd love to see instructions for using this with WebUI.

The Oobabooga standard API  is compatible with KoboldAI requests. Follow the above instructions, just change the address to Oobabooga's API address.

Cheers!
